image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - betterthantomorrow.calva

tasks:
    - init: |
          cd todomvc && npm install && npx shadow-cljs compile app
    - command: |
          cd todomvc && npx shadow-cljs watch app
