image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - betterthantomorrow.calva

tasks:
    - init: |
          npm install && npx shadow-cljs compile app
    - command: |
          npx shadow-cljs watch app
